name: QPP build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Set up repository access
      uses: actions/checkout@v4   
    - name: Set up Python # host for cibuildwheel
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 
    - name: Install dependencies
      run: python -m pip install setuptools wheel twine cibuildwheel
    - name: Set up JDK               
      uses: actions/setup-java@v4 
      with:
        java-version: 11
        distribution: 'adopt-openj9'
    - name: Build source
      run: ant -noinput -buildfile build.xml dist
    - name: Run cibuildwheel
      env:
        CIBW_ARCHS_MACOS: x86_64 universal2 arm64
      run: python -m cibuildwheel build --output-dir build/dist
    - name: Upload wheel artifact for this OS
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.os }}
        path: build/dist/*.whl
  collect_wheels:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/checkout@v4
      - name: Download all OS wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          merge-multiple: true
          path: collected-wheels/
      - name: Zip all OS wheels
        run: |
          cd collected-wheels
          zip -r ../all-os-wheels.zip .
      - name: Upload combined wheels zip
        uses: actions/upload-artifact@v4
        with:
          name: all-os-wheels
          path: all-os-wheels.zip
